<?php

require_once('config.php');
require_once('file_handling.php');

function playlist_header() {
    return COMMENT_SYMBOL.'Generated by '.APPLICATION_NAME.' v'.APPLICATION_VERSION.', date '.date('Y-m-d (H:i)');
}

function playlist_contents($playlist_path, $data) {
    // Make data paths relative to playlist path, and skip directories
    $playlist_content = array();
    foreach ($data as $file) {
        if (file_exists($file) && !is_dir($file))
            array_push($playlist_content, make_relative_path($playlist_path, $file));
    }
    return $playlist_content;
}

if (isset($_GET['root']) && isset($_GET['path']) && isset($_POST['data'])) {
    $playlist_file_info = get_file_info($_GET['path']);

    // Reference: http://stackoverflow.com/questions/689185/json-decode-returns-null-php
    if (get_magic_quotes_gpc()) {
        // Remove PHP magic quotes 
        $data = stripslashes($_POST['data']);
    }
    else {
        $data = $_POST['data'];
    }
    $data = json_decode($data, true);

    if ($data == null)
        die("Could not parse json data:<br><br>$_POST[data]");

    //~ die("<pre>".print_r($data, true)."</pre>");

    $handle = fopen($playlist_file_info['path'], 'w')
        or die("Could not open file $playlist_file_info[path] for writing");

    fwrite($handle, playlist_header().LINE_BREAK);
    fwrite($handle, implode("\n", playlist_contents($playlist_file_info['path'], $data)));
    fclose($handle);

    echo "Playlist saved successfully";
}
else
    die("Playlist could not be saved: Invalid aguments given");

?>