<?php

require_once('config.php');
require_once('file_handling.php');

function playlist_header() {
    return COMMENT_SYMBOL.'Generated by '.APPLICATION_NAME.' v'.APPLICATION_VERSION.', date '.date('Y-m-d (H:i)');
}

function playlist_contents($playlist_path, $data) {
    // Make data paths relative to playlist path, and skip directories
    $playlist_content = array();
    foreach ($data as $file) {
        if (file_exists($file) && !is_dir($file))
            array_push($playlist_content, make_relative_path($playlist_path, $file));
    }
    return $playlist_content;
}

if (isset($_GET['root']) && isset($_GET['path']) && isset($_POST['data'])) {
    $playlist_file_info = get_file_info($_GET['root'].DIRECTORY_SEPARATOR.$_GET['path']);
    $data = json_decode($_POST['data']);

    $handle = fopen($playlist_file_info['path'], 'w')
        or die("Could not open file $playlist_file_info[path] for writing");

    fwrite($handle, playlist_header().LINE_BREAK);
    fwrite($handle, implode("\n", playlist_contents($playlist_file_info['path'], $data)));
    fclose($handle);

    echo "Playlist saved successfully";
}
else
    die("Playlist could not be saved: Invalid aguments given");

?>