<?php

require_once('config.php');
require_once('file_handling.php');

function playlist_header() {
    return COMMENT_SYMBOL.'Generated by '.APPLICATION_NAME.' v'.APPLICATION_VERSION.', date '.date('Y-m-d (H:i)');
}

if (isset($_GET['root']) && isset($_GET['path']) && isset($_POST['data'])) {
    $playlist_file_info = get_file_info($_GET['root'].DIRECTORY_SEPARATOR.$_GET['path']);
    $data = json_decode($_POST['data']);

    $handle = fopen($playlist_file_info['path'].".test", 'w')
        or die("Could not open file $playlist_file_info[path] for writing");

    fwrite($handle, playlist_header()."\n");
    fwrite($handle, implode("\n", $data));
    fclose($handle);

    echo "Playlist saved successfully";
    echo "<br><br>Contents:";
    foreach ($data as $item)
        echo "<br> * $item";
}
else
    die("Playlist could not be saved: Invalid aguments given");

?>